<?php

define("DATABASE_HOST", "VOTRE HOST");
define("DATABASE_NAME", "VOTRE NOM DE BDD");
define("DATABASE_USERNAME", "VOTRE NOM");
define("DATABASE_PASSWORD", "VOTRE MDP");

define("BASE_API_URL", "METTRE VOTRE BASE API");
define("API_STUDENT", BASE_API_URL . "/student");

define("CORS_ALLOWED_ORIGINS", "*");
